### ISSUE TITLE
How to provide a way to set custom `$gitpromptsettings`

### ISSUE THREAD

**Issue by Jawz84** [bergmeister/lazy-posh-git#1]
I'm enhusiastic about lazy-posh-git. Simple, effective, nice!

My only issue so far: I can't set custom settings for posh-git in my profile anymore.

```powershell
import-module lazy-posh-git
$GitPromptSettings.DefaultPromptAbbreviateHomeDirectory = $true
$GitPromptSettings.AfterStatus.Text = "]`n"
```
Ofcourse fails with:
```text
InvalidOperation: C:\Users\user\Documents\PowerShell\profile.ps1:2
Line |
   2 |  $GitPromptSettings.DefaultPromptAbbreviateHomeDirectory = $true
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'DefaultPromptAbbreviateHomeDirectory' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: C:\Users\user\Documents\PowerShell\profile.ps1:3
Line |
   3 |  $GitPromptSettings.AfterPath = "]`n"
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'AfterPath' cannot be found on this object. Verify that the property exists and can be set.
```

This makes sense: the variable `$GitPromptSettings` is not created yet, since we are deferring the import of the posh-git module until a later moment in time. 

Related issue: https://github.com/dahlbyk/posh-git/issues/635

Since `posh-git` does not support a settings file at this time, I thought about adding delayed settings load to `lazy-posh-git`. There could be various ways of doing this. 

One way would be to support a settings script that, if it exists, could be loaded after importing `posh-git`:

```powershell
...
        if (Test-Path (Join-Path $PWD.Path '.git')) {
            Import-Module posh-git
            if (Test-Path (Join-Path $PsScriptroot settings.ps1)) {
                . (Join-Path $PsScriptroot settings.ps1)
            }
        }
...
```
Where there can be a `settings.ps1` file in the root of the `lazy-posh-git` module with a settingsfile like this:
```powershell
$GitPromptSettings.DefaultPromptAbbreviateHomeDirectory = $true
$GitPromptSettings.AfterStatus.Text = "]`n"
```

I'm curious about your thoughts on this.

**Comment by bergmeister** [comment]
Happy to incorporate that and didn't know about that. Why dot-sourcing this custom post-import script and not using `&` operator?
Also, `Import-Module` seems to have a `ArgumentList` parameter so we could potentially offer a parameter so that people can optionally pass in the name to this custom post-import script.

**Comment by Jawz84** [comment]
I've created a PR for convenience, feel free to make changes to it, or merge as is :)
